services:
  database:
    build:
      context: ./database/sqlserver
    profiles: ["dev"]
    container_name: sqlserver-database
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      SA_PASSWORD: "sq1server@Admin"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"

  api:
    build:
      context: ./backend
      target: development
    image: enic_mis_api:dev
    profiles: ["dev"]
    container_name: aspnet-api
    depends_on:
      - database
    ports:
      - "5029:8080"
    volumes:
      - ./backend:/app
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: Development

  web:
    build:
      context: ./frontend
      target: development
    image: enic_mis_client:dev
    profiles: ["dev"]
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_APP_VERSION=dev
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://api:8080
    stdin_open: true
    tty: true

  api-prod:
    build:
      context: ./backend
      target: production
    image: enic_mis_api:${APP_VERSION}
    profiles: ["prod"]
    container_name: aspnet-api-prod
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
    environment:
      APP_VERSION: ${APP_VERSION}
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: Production

  web-prod:
    build:
      context: ./frontend
      target: production
    image: enic_mis_client:${APP_VERSION}
    profiles: ["prod"]
    container_name: react-frontend-prod
    ports:
      - "8000:80"
    stdin_open: true
    tty: true
    environment:
      - VITE_APP_VERSION=${APP_VERSION}

volumes:
  mssql-data:
  dataprotection-keys:
