name: API CI

on:
  push:
    branches: "**"
  pull_request:
    branches: [main]

jobs:
  restore:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3

      - name: Restore dependencies
        run: nix develop .# --command bash -c "cd backend && dotnet restore"

  format:
    needs: restore
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3

      - name: Check formatting
        run: nix develop .# --command bash -c "cd backend && dotnet restore && dotnet format --verify-no-changes --no-restore"

  lint:
    needs: restore
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3

      - name: Check linting
        run: |
          nix develop .# --command bash -c "
            cd backend && dotnet restore && dotnet build \
              /p:EnforceCodeStyleInBuild=true \
              /p:AnalysisLevel=latest \
              /p:TreatWarningsAsErrors=false \
              /warnaserror
          "

  build:
    needs: [format, lint]
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: nix develop .# --command bash -c "cd backend && dotnet restore && dotnet build --no-restore"

  code-quality:
    needs: build
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3

      - name: Check Code Quality
        run: |
          nix develop .# --command bash -c "
            cd backend && dotnet restore && dotnet build --no-restore \
              /p:EnforceCodeStyleInBuild=true \
              /p:AnalysisLevel=latest \
              /p:TreatWarningsAsErrors=false \
              /warnaserror
          "

  test:
    needs: build
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: nix develop .# --command bash -c "cd backend && dotnet restore && dotnet test --no-build --verbosity normal"

  all-checks-passed:
    needs: [code-quality, test]
    runs-on: [self-hosted, linux]
    steps:
      - name: All checks passed
        run: echo "All checks passed for API successfully!"
