name: Client CI 

on:
  push:
    branches: "**"
  pull_request:
    branches: [main]

jobs:
  test-frontend:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v3
      # Uncomment this if you are not going to self-host the actions
      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '24'
      #     cache: 'npm'
      #     cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Check code quality (lint)
        run: cd frontend && npm run lint

      - name: Check formatting (prettier)
        run: cd frontend && npm run format:check

      - name: Type check
        run: cd frontend && npm run type-check

      - name: Verify build
        run: cd frontend && npm run build

  all-checks-passed:
    needs: [ test-frontend ]
    runs-on: [ self-hosted, nixos ]
    steps:
      - name: All checks passed
        run: echo "All tests passed for frontend successfully!"
